addSbtPlugin("edu.gemini"     % "sbt-lucuma-lib"      % "0.11.3")
addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("io.gatling"     % "gatling-sbt"         % "4.4.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.11.0")
