addSbtPlugin("edu.gemini"     % "sbt-lucuma-lib"      % "0.12.8")
addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.1")
addSbtPlugin("io.gatling"     % "gatling-sbt"         % "4.13.3")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.13.1")
